project: 
  type: website

execute:
  keep-md: false
  freeze: auto

website: 
  title: "análise descritiva RAMT provisória"
  navbar:
    left: 
      - principal.qmd

format: 
  html: 
    theme: journal
    code-fold: true
    code-summary: "veja o código"
    # --- NOVAS CONFIGURAÇÕES ABAIXO ---
    toc: true              # Ativa o Sumário (Menu lateral)
    toc-depth: 3           # Define até qual nível de título aparece (h1, h2, h3)
    toc-location: right    # Posiciona o menu à direita (pode ser 'left')
    toc-title: "Nesta página" # Título customizado do menu
    number-sections: true  # Opcional: enumera os títulos automaticamente
    anchor-sections: true  # Cria links clicáveis ao passar o mouse nos títulos

mainfont: sans-serif