project:
  type: website

website:
  title: "EcoHub"
  favicon: assets/favicon.svg
  search: true
  repo-url: "https://github.com/fernandovieira1/ambiental_bd_usp"
  navbar:
    logo: assets/logo.svg
    left:
      - text: Início
        href: index.qmd
      - text: Suporte
        href: suporte.qmd
      - text: Equipe
        href: equipe.qmd
      - text: Sobre
        href: sobre.qmd
    tools:
      - icon: list
        aria-label: "Menu"
        href: "javascript:void(0)"   # não navega; o JS abre a gaveta
  page-footer:
    center: "© {{< meta year >}} EcoHub"

format:
  html:
    theme: [default]                  # mantém o tema base
    css: assets/styles.scss           # seu SCSS customizado
    toc: false
    smooth-scroll: true
    include-in-header: _includes/header.html
    include-before-body: _includes/drawer.html
    include-after-body: _includes/scripts.html
