### Sub 1 ####
df_novot <- df_novo2 %>%
  mutate(origem = case_when(
    # --- Correções Acre (AC) ---
    origem == "assis brasi" ~ "Assis Brasil",
    origem == "placido decastro" ~ "Plácido de Castro",
    
    # --- Correções Alagoas (AL) ---
    origem == "matriz do camaragibe" ~ "Matriz de Camaragibe",
    origem == "sao jose da lage" ~ "São José da Laje",
    origem == "sao miguel do campos" ~ "São Miguel dos Campos",
    origem == "sao luiz do quitunde" ~ "São Luís do Quitunde",
    
    # --- Correções Amazonas (AM) ---
    origem == "boa vista dos ramos" ~ "Boa Vista do Ramos",
    origem == "santo / antonio do ica" ~ "Santo Antônio do Içá",
    origem == "manues" ~ "Maués",
    
    # --- Correções Amapá (AP) ---
    origem == "santama" ~ "Santana",
    
    # --- Correções Bahia (BA) ---
    origem == "ibirapoa" ~ "Ibirapoã",
    origem == "barro preto/lomanto junior" ~ "Barro Preto",
    origem == "lafayette coutinho" ~ "Lafaiete Coutinho",
    origem == "lagedo do tabocal" ~ "Lajedo do Tabocal",
    origem == "lomanto junior" ~ "Barro Preto",
    origem == "bicuri" ~ "Ibicuí",
    origem == "morpora" ~ "Morpará",
    
    # --- Correções Ceará (CE) ---
    origem == "potangi" ~ "Potengi",
    
    # --- Correções Cidades com estado incorreto ---
    origem == "campos belos" ~ "Campos Belos",
    origem == "monte alegre" ~ "Monte Alegre de Goiás",
    origem == "nova roma" ~ "Nova Roma",
    origem == "divinopolis de goias" ~ "Divinópolis de Goiás",
    origem == "sao domingos" ~ "São Domingos",
    origem == "guarani de goias" ~ "Guarani de Goiás",
    origem == "iaciara" ~ "Iaciara",
    origem == "posse" ~ "Posse",
    origem == "alvorada do norte" ~ "Alvorada do Norte",
    origem == "flores de goias" ~ "Flores de Goiás",
    origem == "vila boa" ~ "Vila Boa",
    origem == "simolandia" ~ "Simolândia",
    origem == "buritis" ~ "Buritis",
    origem == "buritinopolis" ~ "Buritinópolis",
    origem == "mambai" ~ "Mambaí",
    origem == "damianopolis" ~ "Damianópolis",
    origem == "sitio de abadia" ~ "Sítio d'Abadia",
    origem == "arinos" ~ "Arinos",
    origem == "uruana de minas" ~ "Uruana de Minas",
    origem == "unai" ~ "Unaí",
    origem == "cabeceira grande" ~ "Cabeceira Grande",
    origem == "cristalina" ~ "Cristalina",
    origem == "luziania" ~ "Luziânia",
    origem == "valparaiso de goias" ~ "Valparaíso de Goiás",
    origem == "novo gama" ~ "Novo Gama",
    origem == "cidade ocidental" ~ "Cidade Ocidental",
    origem == "alexania" ~ "Alexânia",
    origem == "corumba de goias" ~ "Corumbá de Goiás",
    origem == "aguas lindas de goias" ~ "Águas Lindas de Goiás",
    origem == "santo antonio do descoberto" ~ "Santo Antônio do Descoberto",
    origem == "padre bernardo" ~ "Padre Bernardo",
    origem == "cocalzinho de goias" ~ "Cocalzinho de Goiás",
    origem == "mimoso" ~ "Mimoso de Goiás",
    origem == "sao joao dalianca" ~ "São João d'Aliança",
    origem == "formosa" ~ "Formosa",
    origem == "agua fria" ~ "Água Fria de Goiás",
    origem == "cabeceiras" ~ "Cabeceiras",
    origem == "alto paraiso de goias" ~ "Alto Paraíso de Goiás",
    origem == "cavalcante" ~ "Cavalcante",
    origem == "colinas do sul" ~ "Colinas do Sul",
    origem == "teresina de goias" ~ "Teresina de Goiás",
    origem == "distrito federal" ~ "Distrito Federal",
    origem == "sitio dabadia" ~ "Sítio d'Abadia",
    origem == "agua fria de goias" ~ "Água Fria de Goiás",
    origem == "chapada gaucha" ~ "Chapada Gaúcha",
    origem == "pintopolis" ~ "Pintópolis",
    origem == "riachinho" ~ "Riachinho",
    origem == "urucuia" ~ "Urucuia",
    origem == "bonfinopolis de minas" ~ "Bonfinópolis de Minas",
    origem == "brasilandia de minas" ~ "Brasilândia de Minas",
    origem == "dom bosco" ~ "Dom Bosco",
    origem == "natalandia" ~ "Natalândia",
    
    # --- Correções Espírito Santo (ES) ---
    origem == "atilio / vivacqua" ~ "Atílio Vivácqua",
    
    # --- Correções Goiás (GO) ---
    origem == "aragarcas" ~ "Aragarças",
    origem == "araguapaz" ~ "Araguapaz",
    origem == "arenopolis" ~ "Arenópolis",
    origem == "aruana" ~ "Aruanã",
    origem == "baliza" ~ "Baliza",
    origem == "bom jardim de goias" ~ "Bom Jardim de Goiás",
    origem == "britania" ~ "Britânia",
    origem == "crixas" ~ "Crixás",
    origem == "diorama" ~ "Diorama",
    origem == "faina" ~ "Faina",
    origem == "goias" ~ "Goiás",
    origem == "itapirapua" ~ "Itapirapuã",
    origem == "jussara" ~ "Jussara",
    origem == "matrincha" ~ "Matrinchã",
    origem == "montes claros de goias" ~ "Montes Claros de Goiás",
    origem == "mozarlandia" ~ "Mozarlândia",
    origem == "mundo novo" ~ "Mundo Novo",
    origem == "nova crixas" ~ "Nova Crixás",
    origem == "novo planalto" ~ "Novo Planalto",
    origem == "piranhas" ~ "Piranhas",
    origem == "santa fe de goias" ~ "Santa Fé de Goiás",
    origem == "sao miguel do araguaia" ~ "São Miguel do Araguaia",
    origem == "uirapuru" ~ "Uirapuru",
    origem == "alto horizonte" ~ "Alto Horizonte",
    origem == "amaralina" ~ "Amaralina",
    origem == "bonopolis" ~ "Bonópolis",
    origem == "campinacu" ~ "Campinaçu",
    origem == "campinorte" ~ "Campinorte",
    origem == "campos verdes" ~ "Campos Verdes",
    origem == "estrela do norte" ~ "Estrela do Norte",
    origem == "formoso" ~ "Formoso",
    origem == "mara rosa" ~ "Mara Rosa",
    
    origem == "minacu" ~ "Minaçu",
    origem == "montividiu do norte" ~ "Montividiu do Norte",
    origem == "mutunopolis" ~ "Mutunópolis",
    origem == "niquelandia" ~ "Niquelândia",
    origem == "nova iguacu de goias" ~ "Nova Iguaçu de Goiás",
    origem == "porangatu" ~ "Porangatu",
    origem == "santa tereza de goias" ~ "Santa Tereza de Goiás",
    origem == "santa terezinha de goias" ~ "Santa Terezinha de Goiás",
    origem == "trombas" ~ "Trombas",
    origem == "uruacu" ~ "Uruaçu",
    origem == "barro alto" ~ "Barro Alto",
    origem == "carmo do rio verde" ~ "Carmo do Rio Verde",
    origem == "ceres" ~ "Ceres",
    origem == "goianesia" ~ "Goianésia",
    origem == "guarinos" ~ "Guarinos",
    origem == "hidrolina" ~ "Hidrolina",
    origem == "ipiranga de goias" ~ "Ipiranga de Goiás",
    origem == "itapaci" ~ "Itapaci",
    origem == "morro agudo de goias" ~ "Morro Agudo de Goiás",
    origem == "nova america" ~ "Nova América",
    origem == "nova gloria" ~ "Nova Glória",
    origem == "pilar de goias" ~ "Pilar de Goiás",
    origem == "rialma" ~ "Rialma",
    origem == "rianapolis" ~ "Rianápolis",
    origem == "rubiataba" ~ "Rubiataba",
    origem == "santa isabel" ~ "Santa Isabel",
    origem == "santa rita do novo destino" ~ "Santa Rita do Novo Destino",
    origem == "sao luiz do norte" ~ "São Luiz do Norte",
    origem == "sao patricio" ~ "São Patrício",
    origem == "vila propicio" ~ "Vila Propício",
    origem == "adelandia" ~ "Adelândia",
    origem == "americano do brasil" ~ "Americano do Brasil",
    origem == "amorinopolis" ~ "Amorinópolis",
    origem == "aurilandia" ~ "Aurilândia",
    origem == "buriti de goias" ~ "Buriti de Goiás",
    origem == "cachoeira de goias" ~ "Cachoeira de Goiás",
    origem == "corrego do ouro" ~ "Córrego do Ouro",
    origem == "damolandia" ~ "Damolândia",
    origem == "fazenda nova" ~ "Fazenda Nova",
    origem == "firminopolis" ~ "Firminópolis",
    origem == "guaraita" ~ "Guaraíta",
    origem == "heitorai" ~ "Heitoraí",
    origem == "ipora" ~ "Iporá",
    origem == "israelandia" ~ "Israelândia",
    origem == "itaberai" ~ "Itaberaí",
    origem == "itaguari" ~ "Itaguari",
    origem == "itaguaru" ~ "Itaguaru",
    origem == "itapuranga" ~ "Itapuranga",
    origem == "itaucu" ~ "Itauçu",
    origem == "ivolandia" ~ "Ivolândia",
    origem == "jaragua" ~ "Jaraguá",
    origem == "jaupaci" ~ "Jaupaci",
    origem == "jesupolis" ~ "Jesúpolis",
    origem == "moipora" ~ "Moiporá",
    origem == "mossamedes" ~ "Mossâmedes",
    origem == "novo brasil" ~ "Novo Brasil",
    origem == "petrolina de goias" ~ "Petrolina de Goiás",
    origem == "pirenopolis" ~ "Pirenópolis",
    origem == "sanclerlandia" ~ "Sanclerlândia",
    origem == "santa rosa de goias" ~ "Santa Rosa de Goiás",
    origem == "sao francisco de goias" ~ "São Francisco de Goiás",
    origem == "sao luis de montes belos" ~ "São Luís de Montes Belos",
    origem == "taquaral de goias" ~ "Taquaral de Goiás",
    origem == "turvania" ~ "Turvânia",
    origem == "uruana" ~ "Uruana",
    origem == "abadia de goias" ~ "Abadia de Goiás",
    origem == "abadiania" ~ "Abadiânia",
    origem == "anapolis" ~ "Anápolis",
    origem == "anicuns" ~ "Anicuns",
    origem == "aparecida de goiania" ~ "Aparecida de Goiânia",
    origem == "aracu" ~ "Araçu",
    origem == "aragoiania" ~ "Aragoiânia",
    origem == "avelinopolis" ~ "Avelinópolis",
    origem == "bela vista de goias" ~ "Bela Vista de Goiás",
    origem == "bonfinopolis" ~ "Bonfinópolis",
    origem == "brazabrantes" ~ "Brazabrantes",
    origem == "caldazinha" ~ "Caldazinha",
    origem == "campo limpo de goias" ~ "Campo Limpo de Goiás",
    origem == "caturai" ~ "Caturaí",
    origem == "goianapolis" ~ "Goianápolis",
    origem == "goiania" ~ "Goiânia",
    origem == "goianira" ~ "Goianira",
    origem == "guapo" ~ "Guapó",
    origem == "hidrolandia" ~ "Hidrolândia",
    origem == "inhumas" ~ "Inhumas",
    origem == "leopoldo de bulhoes" ~ "Leopoldo de Bulhões",
    origem == "nazario" ~ "Nazário",
    origem == "neropolis" ~ "Nerópolis",
    origem == "nova veneza" ~ "Nova Veneza",
    origem == "ouro verde de goias" ~ "Ouro Verde de Goiás",
    origem == "santa barbara de goias" ~ "Santa Bárbara de Goiás",
    origem == "santo antonio de goias" ~ "Santo Antônio de Goiás",
    origem == "senador canedo" ~ "Senador Canedo",
    origem == "terezopolis de goias" ~ "Terezópolis de Goiás",
    origem == "trindade" ~ "Trindade",
    origem == "caiaponia" ~ "Caiapônia",
    origem == "doverlandia" ~ "Doverlândia",
    origem == "palestina de goias" ~ "Palestina de Goiás",
    origem == "parauna" ~ "Paraúna",
    origem == "sao joao da parauna" ~ "São João da Paraúna",
    origem == "aloandia" ~ "Aloândia",
    origem == "campestre de goias" ~ "Campestre de Goiás",
    origem == "cezarina" ~ "Cezarina",
    origem == "cristianopolis" ~ "Cristianópolis",
    origem == "crominia" ~ "Cromínia",
    origem == "edealina" ~ "Edealina",
    origem == "indiara" ~ "Indiara",
    origem == "jandaia" ~ "Jandaia",
    origem == "joviania" ~ "Joviânia",
    origem == "mairipotaba" ~ "Mairipotaba",
    origem == "morrinhos" ~ "Morrinhos",
    origem == "palmeiras de goias" ~ "Palmeiras de Goiás",
    origem == "palmelo" ~ "Palmelo",
    origem == "palminopolis" ~ "Palminópolis",
    origem == "piracanjuba" ~ "Piracanjuba",
    origem == "pires do rio" ~ "Pires do Rio",
    origem == "pontalina" ~ "Pontalina",
    origem == "professor jamil" ~ "Professor Jamil",
    origem == "rio quente" ~ "Rio Quente",
    origem == "santa cruz de goias" ~ "Santa Cruz de Goiás",
    origem == "sao miguel do passa quatro" ~ "São Miguel do Passa Quatro",
    origem == "urutai" ~ "Urutaí",
    origem == "varjao" ~ "Varjão",
    origem == "vicentinopolis" ~ "Vicentinópolis",
    origem == "agua limpa" ~ "Água Limpa",
    origem == "anhanguera" ~ "Anhanguera",
    origem == "buriti alegre" ~ "Buriti Alegre",
    origem == "cachoeira dourada" ~ "Cachoeira Dourada",
    
    origem == "caldas novas" ~ "Caldas Novas",
    origem == "campo alegre de goias" ~ "Campo Alegre de Goiás",
    origem == "catalao" ~ "Catalão",
    origem == "corumbaiba" ~ "Corumbaíba",
    origem == "cumari" ~ "Cumari",
    origem == "davinopolis" ~ "Davinópolis",
    origem == "gameleira de goias" ~ "Gameleira de Goiás",
    origem == "goiandira" ~ "Goiandira",
    origem == "inaciolandia" ~ "Inaciolândia",
    origem == "ipameri" ~ "Ipameri",
    origem == "itumbiara" ~ "Itumbiara",
    origem == "marzagao" ~ "Marzagão",
    origem == "nova aurora" ~ "Nova Aurora",
    origem == "orizona" ~ "Orizona",
    origem == "ouvidor" ~ "Ouvidor",
    origem == "panama" ~ "Panamá",
    origem == "silvania" ~ "Silvânia",
    origem == "tres ranchos" ~ "Três Ranchos",
    origem == "vianopolis" ~ "Vianópolis",
    origem == "acreuna" ~ "Acreúna",
    origem == "bom jesus de goias" ~ "Bom Jesus de Goiás",
    origem == "castelandia" ~ "Castelândia",
    origem == "chapadao do ceu" ~ "Chapadão do Céu",
    origem == "edeia" ~ "Edéia",
    origem == "goiatuba" ~ "Goiatuba",
    origem == "gouvelandia" ~ "Gouvelândia",
    origem == "jatai" ~ "Jataí",
    origem == "maurilandia" ~ "Maurilândia",
    origem == "mineiros" ~ "Mineiros",
    origem == "montividiu" ~ "Montividiu",
    origem == "perolandia" ~ "Perolândia",
    origem == "porteirao" ~ "Porteirão",
    origem == "portelandia" ~ "Portelândia",
    origem == "quirinopolis" ~ "Quirinópolis",
    origem == "rio verde" ~ "Rio Verde",
    origem == "santa helena de goias" ~ "Santa Helena de Goiás",
    origem == "santa rita do araguaia" ~ "Santa Rita do Araguaia",
    origem == "santo antonio da barra" ~ "Santo Antônio da Barra",
    origem == "turvelandia" ~ "Turvelândia",
    origem == "aparecida do rio doce" ~ "Aparecida do Rio Doce",
    origem == "apore" ~ "Aporé",
    origem == "cachoeira alta" ~ "Cachoeira Alta",
    origem == "cacu" ~ "Caçu",
    origem == "itaja" ~ "Itajá",
    origem == "itaruma" ~ "Itarumã",
    origem == "lagoa santa" ~ "Lagoa Santa",
    origem == "paranaiguara" ~ "Paranaiguara",
    origem == "sao simao" ~ "São Simão",
    origem == "serranopolis" ~ "Serranópolis",
    
    # --- Correções Maranhão (MA) ---
    origem == "itapecuru-mirim" ~ "Itapecuru Mirim",
    origem == "buri" ~ "Buriti",
    origem == "buri bravo" ~ "Buriti Bravo",
    
    # --- Correções Minas Gerais (MG) ---
    origem == "limeira doeste" ~ "Limeira do Oeste",
    origem == "santa / vitoria" ~ "Santa Vitória",
    origem == "gameleira" ~ "Gameleiras",
    origem == "cachoeira do pajeu" ~ "Cachoeira do Pajeú",
    origem == "pontos dos volantes" ~ "Ponto dos Volantes",
    origem == "santa do paraiso" ~ "Santana do Paraíso",
    origem == "sao geraldo do baixo" ~ "São Geraldo do Baixio",
    origem == "jampruta" ~ "Jampruca",
    origem == "frei inocencia" ~ "Frei Inocêncio",
    origem == "santa cruz do escal vado" ~ "Santa Cruz do Escalvado",
    origem == "santanado manhuacu" ~ "Santana do Manhuaçu",
    origem == "tres pontas-boa esperanca" ~ "Três Pontas e Boa Esperança",
    origem == "englobando 82 municipios: alfenas" ~ "Alfenas",
    origem == "verdelandiabonito de minas" ~ "Verdelândia e Bonito de Minas",
    origem == "conego ma- rinho" ~ "Cônego Marinho",
    origem == "gua- raciama" ~ "Guaraciama",
    origem == "no- vorizonte" ~ "Novorizonte",
    origem == "varjao de minasvazantecoromandel" ~ "Varjão de Minas, Vazante e Coromandel",
    
    # --- Correções Mato Grosso (MT) ---
    origem == "novaguarita" ~ "Nova Guarita",
    origem == "ila rica" ~ "Vila Rica",
    origem == "nossasenhora do livramento" ~ "Nossa Senhora do Livramento",
    origem == "cuiabae varzea grande" ~ "Cuiabá e Várzea Grande",
    origem == "vila bela da s trindade" ~ "Vila Bela da Santíssima Trindade",
    origem == "pontes / lacerda" ~ "Pontes e Lacerda",
    origem == "conquista d oeste" ~ "Conquista d'Oeste",
    origem == "vale do sao domingos" ~ "Vale de São Domingos",
    origem == "sao jose dos 4 marcos" ~ "São José dos Quatro Marcos",
    origem == "gloria d oeste" ~ "Glória d'Oeste",
    origem == "figueiropolis d oeste" ~ "Figueirópolis d'Oeste",
    origem == "campo novo dos parecis" ~ "Campo Novo do Parecis",
    origem == "alto garca" ~ "Alto Garças",
    origem == "santa teresinha" ~ "Santa Terezinha",
    origem == "mirassol d oeste" ~ "Mirassol d'Oeste",
    origem == "lambari d oeste" ~ "Lambari d'Oeste",
    origem == "n senhora do livramento" ~ "Nossa Senhora do Livramento",
    origem == "lambari do oeste" ~ "Lambari d'Oeste",
    origem == "mirassol do oeste" ~ "Mirassol d'Oeste",
    
    # --- Correções Pará (PA) ---
    origem == "de anapu" ~ "Anapu",
    origem == "de alenquer" ~ "Alenquer",
    origem == "itaitubas" ~ "Itaituba",
    origem == "monjui dos campos" ~ "Mojuí dos Campos",
    origem == "breu branc" ~ "Breu Branco",
    origem == "ucurui" ~ "Tucuruí",
    origem == "novo repartimento e breu branco" ~ "Novo Repartimento e Breu Branco",
    origem == "igarape miri" ~ "Igarapé-Miri",
    origem == "peixe boi" ~ "Peixe-Boi",
    origem == "tracuateua e viseu" ~ "Tracuateua e Viseu",
    
    # --- Correções Paraíba (PB) ---
    origem == "gua branca" ~ "Água Branca",
    origem == "bernadino batista" ~ "Bernardino Batista",
    origem == "poco jose de moura" ~ "Poço de José de Moura",
    origem == "sao jose do espinharas" ~ "São José do Espinharas",
    origem == ": alagoagrande" ~ "Alagoa Grande",
    origem == "campodesantana" ~ "Tacima", # Nome atual de Campo de Santana
    origem == "riachaodo bacamarte" ~ "Riachão do Bacamarte",
    origem == "sao sebastiaodelagoa de roca" ~ "São Sebastião de Lagoa de Roça",
    
    # --- Correções Paraíba (PB) ---
    origem == "aguabranca" ~ "Água Branca",
    origem == "maedagua" ~ "Mãe d'Água",
    origem == "princesaisabel" ~ "Princesa Isabel",
    origem == "saojosedecaiana" ~ "São José de Caiana",
    origem == "tavares todos os municipios estaolocalizados nos limites da mesorregiao do sertao" ~ "Tavares",
    origem == "nas microrregioes de catole do rocha" ~ "Catolé do Rocha",
    
    # --- Correções Pernambuco (PE) ---
    origem == "abare" ~ "Abaré",
    origem == "chorrocho" ~ "Chorrochó",
    origem == "curaca" ~ "Curaçá",
    origem == "gloria" ~ "Glória",
    origem == "macurure" ~ "Macururé",
    origem == "rodelas" ~ "Rodelas",
    origem == "abreu / lima" ~ "Abreu e Lima",
    origem == "agua peta" ~ "Água Preta",
    
    # --- Correções Piauí (PI) ---
    origem == "sao joao da fronteira e sao jose do divino" ~ "São João da Fronteira e São José do Divino",
    origem == "tasso fragoso" ~ "Alto Parnaíba",
    origem == ": canavieira" ~ "Canavieira",
    origem == "milagres do maranhao" ~ "Milagres do Maranhão",
    
    # --- Correções Paraná (PR) ---
    origem == "ura" ~ "Uraí",
    origem == "uniflor e xambre" ~ "Uniflor e Xambrê",
    origem == "jandaia do sull" ~ "Jandaia do Sul",
    origem == "uniao da vitoria e ventania" ~ "União da Vitória e Ventania",
    
    # --- Correções Rio de Janeiro (RJ) ---
    origem == "conceicao do macabu" ~ "Conceição de Macabu",
    origem == "teresopolis e trajano de moraes" ~ "Teresópolis e Trajano de Moraes",
    origem == "sao jose de uba e varre-sai" ~ "São José de Ubá e Varre-Sai",
    origem == "armacao de buzios" ~ "Armação dos Búzios",
    origem == "saquarema e silva jardim" ~ "Saquarema e Silva Jardim",
    origem == "sao francisco do itabapoana" ~ "São Francisco de Itabapoana",
    
    # --- Correções Rio Grande do Norte (RN) ---
    origem == "joao camara/rn abrangencia: bento fernandes" ~ "João Câmara e Bento Fernandes",
    origem == "passa / fica" ~ "Passa e Fica",
    origem == "sao rafae" ~ "São Rafael",
    origem == "lajes pintada" ~ "Lajes Pintadas",
    origem == "lagoa d anta" ~ "Lagoa d'Anta",
    origem == "doutor • severiano" ~ "Doutor Severiano",
    origem == "olho dagua dos borges" ~ "Olho-d'Água do Borges",
    origem == "sao bento do borte" ~ "São Bento do Norte",
    origem == "senador georgino • avelino" ~ "Senador Georgino Avelino",
    origem == "tenente lautrentino cruz" ~ "Tenente Laurentino Cruz",
    origem == "ceara- mirim" ~ "Ceará-Mirim",
    origem == "governador dix- sept rosado" ~ "Governador Dix-Sept Rosado",
    origem == "triunfo potiguar e upanema" ~ "Triunfo Potiguar e Upanema",
    origem == "venha- ver" ~ "Venha-Ver",
    
    # --- Correções Rondônia (RO) ---
    origem == "pimenteiras doeste" ~ "Pimenteiras do Oeste",
    origem == "alvorada do oeste" ~ "Alvorada d'Oeste",
    origem == "porto velho alto madeira" ~ "Porto Velho",
    origem == "buriɵs" ~ "Buritis",
    origem == "porto velho ponta do abuna" ~ "Porto Velho",
    
    # --- Correções Roraima (RR) ---
    origem == "sao luis" ~ "São Luís",
    
    # --- Correções Rio Grande do Sul (RS) ---
    origem == "uevedos" ~ "Quevedos",
    origem == "sao • vicente do sul" ~ "São Vicente do Sul",
    origem == "barra do • ribeiro" ~ "Barra do Ribeiro",
    origem == "minas do • leao" ~ "Minas do Leão",
    origem == "sentinela • do sul" ~ "Sentinela do Sul",
    origem == "xangri-l" ~ "Xangri-lá",
    origem == "sant ana do livramento" ~ "Sant'Ana do Livramento",
    origem == "porto xavier rolador" ~ "Porto Xavier e Rolador",
    origem == "dilermando aguiar" ~ "Dilermando de Aguiar",
    origem == "tres forquilhas e xangri-la o mrt 08 representa boa parte da faixa litoranea do estado" ~ "Três Forquilhas e Xangri-lá",
    origem == "desde o litoral norte ate o municipio de sao jose do norte" ~ "São José do Norte",
    origem == "dentre eles destacam-se: santa cruz do sul" ~ "Santa Cruz do Sul",
    origem == "ja ao sul do mercado estao os municipios de pantano grande" ~ "Pantano Grande",
    origem == "capela santana" ~ "Capela de Santana",
    
    # --- Correções Santa Catarina (SC) ---
    origem == "lageado grande" ~ "Lajeado Grande",
    origem == "xaxim esta localizada na mesorregiao oeste do estado de santa catarina" ~ "Xaxim",
    origem == "gtalanta" ~ "Atalanta",
    origem == "cohapadoo do laoeado" ~ "Chapadão do Lageado",
    origem == "imabuia" ~ "Imbuia",
    origem == "ituporanoa" ~ "Ituporanga",
    origem == "vidal ramaos" ~ "Vidal Ramos",
    origem == "abelardo luza" ~ "Abelardo Luz",
    origem == "boa jesus" ~ "Bom Jesus",
    origem == "coronel martns" ~ "Coronel Martins",
    origem == "enitre reios" ~ "Entre Rios",
    origem == "galvoo" ~ "Galvão",
    origem == "jupir" ~ "Jupiá",
    origem == "mareaa" ~ "Marema",
    origem == "ponite serrada" ~ "Ponte Serrada",
    origem == "soo doaingos" ~ "São Domingos",
    origem == "vargeoo" ~ "Vargeão",
    origem == "xaxia e" ~ "Xaxim",
    origem == "chapadao do lajeado" ~ "Chapadão do Lageado",
    origem == "videira esta localizada na mesorregiao oeste do estado de santa catarina" ~ "Videira",
    
    # --- Correções Sergipe (SE) ---
    origem == "indiarobae pedrinhas" ~ "Indiaroba e Pedrinhas",
    origem == "taporanga dajuda" ~ "Itaporanga d'Ajuda",
    origem == "caninde do sao francisco" ~ "Canindé de São Francisco",
    origem == "monte alegre" ~ "Monte Alegre de Sergipe",
    origem == "peda mole" ~ "Pedra Mole",
    origem == "sao miguel do aleixo cumbe" ~ "São Miguel do Aleixo e Cumbe",
    
    # --- Correções São Paulo (SP) ---
    origem == "americo de cam- pos" ~ "Américo de Campos",
    origem == "estrela" ~ "Estrela d'Oeste",
    origem == "gua- rani doeste" ~ "Guarani d'Oeste",
    origem == "me- ridiano" ~ "Meridiano",
    
    origem == "nova luzita- nia" ~ "Nova Luzitânia",
    origem == "poti- rendaba" ~ "Potirendaba",
    origem == "dra- cena" ~ "Dracena",
    origem == "muritinga do sul" ~ "Murutinga do Sul",
    origem == "na- randiba" ~ "Narandiba",
    origem == "nova indepedencia" ~ "Nova Independência",
    origem == "salmorao" ~ "Salmourão",
    origem == "brodowisk" ~ "Brodowski",
    origem == "ca- juru" ~ "Cajuru",
    origem == "elisario" ~ "Elisiário",
    origem == "jardi- nopolis" ~ "Jardinópolis",
    origem == "palmares pta" ~ "Palmares Paulista",
    origem == "pa- trocinio pta" ~ "Patrocínio Paulista",
    origem == "sales de oliveira" ~ "Sales Oliveira",
    origem == "itapecerica da terra" ~ "Itapecerica da Serra",
    origem == "santa izabel" ~ "Santa Isabel",
    origem == "jan- dira" ~ "Jandira",
    origem == "campo limpo pau- lista" ~ "Campo Limpo Paulista",
    origem == "embu" ~ "Embu das Artes",
    origem == "pira- caia" ~ "Piracaia",
    origem == "tremembe e redencao as serra" ~ "Tremembé e Redenção da Serra",
    origem == "de guaratingueta" ~ "Guaratinguetá",
    origem == "capi- vari" ~ "Capivari",
    origem == "horto- landia" ~ "Hortolândia",
    origem == "santa barbara do oeste" ~ "Santa Bárbara d'Oeste",
    origem == "santo antonio da posse" ~ "Santo Antônio de Posse",
    origem == "alvin- landia" ~ "Alvinlândia",
    origem == "ca- felandia" ~ "Cafelândia",
    origem == "gua- embe" ~ "Guaimbê",
    origem == "ibirema" ~ "Ibirarema",
    origem == "maduri" ~ "Manduri",
    origem == "perderneiras" ~ "Pederneiras",
    origem == "piratininta" ~ "Piratininga",
    origem == "vera cruz aguas de santa barbara" ~ "Vera Cruz e Águas de Santa Bárbara",
    origem == "tejuca" ~ "Tejupá",
    origem == "ipira" ~ "Iporanga",
    
    # --- Correções Tocantins (TO) ---
    origem == "iguatins" ~ "Itaguatins",
    origem == "riachinho sampaio" ~ "Riachinho e Sampaio",
    origem == "chapada da areia" ~ "Chapada de Areia",
    .default = origem
  ))

library(dplyr)

### Sub 2 ####
df_novot <- df_novot %>%
  mutate(origem = case_when(
    # --- Alagoas (AL) ---
    origem == 'sao jose da lage' ~ "São José da Laje",
    origem == 'sao miguel do campos' ~ "São Miguel dos Campos",
    origem == 'sao luiz do quitunde' ~ "São Luís do Quitunde",
    
    # --- Amazonas (AM) ---
    origem == 'santo' ~ "Santo Antônio do Içá",
    origem == 'antonio do ica' ~ "Santo Antônio do Içá",
    origem == 'manues' ~ "Maués",
    
    # --- Bahia (BA) ---
    origem == 'ibirapoa' ~ "Ibirapoã",
    origem == 'da silva' ~ "(Não foi possível corrigir)",
    origem == 'lomanto junior' ~ "Barro Preto",
    origem == 'morpora' ~ "Morpará",
    
    # --- Ceará (CE) ---
    origem == 'ubajarae vicosa do ceara' ~ "Ubajara e Viçosa do Ceará",
    
    # --- Cidades incorretamente listadas como Distrito Federal (DF) ---
    origem == 'campos belos' ~ "Campos Belos",
    origem == 'monte alegre de goias' ~ "Monte Alegre de Goiás",
    origem == 'nova roma' ~ "Nova Roma",
    origem == 'divinopolis de goias' ~ "Divinópolis de Goiás",
    origem == 'sao domingos' ~ "São Domingos",
    origem == 'guarani de goias' ~ "Guarani de Goiás",
    origem == 'iaciara' ~ "Iaciara",
    origem == 'posse' ~ "Posse",
    origem == 'alvorada do norte' ~ "Alvorada do Norte",
    origem == 'flores de goias' ~ "Flores de Goiás",
    origem == 'vila boa' ~ "Vila Boa",
    origem == 'simolandia' ~ "Simolândia",
    origem == 'buritis' ~ "Buritis",
    origem == 'buritinopolis' ~ "Buritinópolis",
    origem == 'mambai' ~ "Mambaí",
    origem == 'damianopolis' ~ "Damianópolis",
    origem == 'sitio de abadia' ~ "Sítio d'Abadia",
    origem == 'formoso' ~ "Formoso",
    origem == 'arinos' ~ "Arinos",
    origem == 'uruana de minas' ~ "Uruana de Minas",
    origem == 'unai' ~ "Unaí",
    origem == 'cabeceira grande' ~ "Cabeceira Grande",
    origem == 'cristalina' ~ "Cristalina",
    origem == 'luziania' ~ "Luziânia",
    origem == 'valparaiso de goias' ~ "Valparaíso de Goiás",
    origem == 'novo gama' ~ "Novo Gama",
    origem == 'cidade ocidental' ~ "Cidade Ocidental",
    origem == 'alexania' ~ "Alexânia",
    origem == 'corumba de goias' ~ "Corumbá de Goiás",
    origem == 'aguas lindas de goias' ~ "Águas Lindas de Goiás",
    origem == 'santo antonio do descoberto' ~ "Santo Antônio do Descoberto",
    origem == 'padre bernardo' ~ "Padre Bernardo",
    origem == 'cocalzinho de goias' ~ "Cocalzinho de Goiás",
    origem == 'mimoso' ~ "Mimoso de Goiás",
    origem == 'sao joao dalianca' ~ "São João d'Aliança",
    origem == 'formosa' ~ "Formosa",
    origem == 'agua fria' ~ "Água Fria de Goiás",
    origem == 'cabeceiras' ~ "Cabeceiras",
    origem == 'alto paraiso de goias' ~ "Alto Paraíso de Goiás",
    origem == 'cavalcante' ~ "Cavalcante",
    origem == 'colinas do sul' ~ "Colinas do Sul",
    origem == 'teresina de goias' ~ "Teresina de Goiás",
    origem == 'distrito federal' ~ "Distrito Federal",
    origem == 'sitio dabadia' ~ "Sítio d'Abadia",
    origem == 'agua fria de goias' ~ "Água Fria de Goiás",
    origem == 'chapada gaucha' ~ "Chapada Gaúcha",
    origem == 'pintopolis' ~ "Pintópolis",
    origem == 'riachinho' ~ "Riachinho",
    origem == 'urucuia' ~ "Urucuia",
    origem == 'bonfinopolis de minas' ~ "Bonfinópolis de Minas",
    origem == 'brasilandia de minas' ~ "Brasilândia de Minas",
    origem == 'dom bosco' ~ "Dom Bosco",
    origem == 'natalandia' ~ "Natalândia",
    
    # --- Espírito Santo (ES) ---
    origem == 'atilio' ~ "Atílio Vivácqua",
    origem == 'vivacqua' ~ "Atílio Vivácqua",
    
    # --- Goiás (GO) ---
    origem == 'aragarcas' ~ "Aragarças",
    origem == 'araguapaz' ~ "Araguapaz",
    origem == 'arenopolis' ~ "Arenópolis",
    origem == 'aruana' ~ "Aruanã",
    origem == 'baliza' ~ "Baliza",
    origem == 'bom jardim de goias' ~ "Bom Jardim de Goiás",
    origem == 'britania' ~ "Britânia",
    origem == 'crixas' ~ "Crixás",
    origem == 'diorama' ~ "Diorama",
    origem == 'faina' ~ "Faina",
    origem == 'goias' ~ "Goiás",
    origem == 'itapirapua' ~ "Itapirapuã",
    origem == 'jussara' ~ "Jussara",
    origem == 'matrincha' ~ "Matrinchã",
    origem == 'montes claros de goias' ~ "Montes Claros de Goiás",
    origem == 'mozarlandia' ~ "Mozarlândia",
    origem == 'mundo novo' ~ "Mundo Novo",
    origem == 'nova crixas' ~ "Nova Crixás",
    origem == 'novo planalto' ~ "Novo Planalto",
    origem == 'piranhas' ~ "Piranhas",
    origem == 'santa fe de goias' ~ "Santa Fé de Goiás",
    origem == 'sao miguel do araguaia' ~ "São Miguel do Araguaia",
    origem == 'uirapuru' ~ "Uirapuru",
    origem == 'alto horizonte' ~ "Alto Horizonte",
    origem == 'amaralina' ~ "Amaralina",
    origem == 'bonopolis' ~ "Bonópolis",
    origem == 'campinacu' ~ "Campinaçu",
    origem == 'campinorte' ~ "Campinorte",
    origem == 'campos verdes' ~ "Campos Verdes",
    origem == 'estrela do norte' ~ "Estrela do Norte",
    origem == 'mara rosa' ~ "Mara Rosa",
    origem == 'minacu' ~ "Minaçu",
    origem == 'montividiu do norte' ~ "Montividiu do Norte",
    origem == 'mutunopolis' ~ "Mutunópolis",
    origem == 'niquelandia' ~ "Niquelândia",
    origem == 'nova iguacu de goias' ~ "Nova Iguaçu de Goiás",
    origem == 'porangatu' ~ "Porangatu",
    origem == 'santa tereza de goias' ~ "Santa Tereza de Goiás",
    origem == 'santa terezinha de goias' ~ "Santa Terezinha de Goiás",
    origem == 'trombas' ~ "Trombas",
    origem == 'uruacu' ~ "Uruaçu",
    origem == 'barro alto' ~ "Barro Alto",
    origem == 'carmo do rio verde' ~ "Carmo do Rio Verde",
    origem == 'ceres' ~ "Ceres",
    origem == 'goianesia' ~ "Goianésia",
    origem == 'guarinos' ~ "Guarinos",
    origem == 'hidrolina' ~ "Hidrolina",
    origem == 'ipiranga de goias' ~ "Ipiranga de Goiás",
    origem == 'itapaci' ~ "Itapaci",
    origem == 'morro agudo de goias' ~ "Morro Agudo de Goiás",
    origem == 'nova america' ~ "Nova América",
    origem == 'nova gloria' ~ "Nova Glória",
    origem == 'pilar de goias' ~ "Pilar de Goiás",
    origem == 'rialma' ~ "Rialma",
    origem == 'rianapolis' ~ "Rianápolis",
    origem == 'rubiataba' ~ "Rubiataba",
    origem == 'santa isabel' ~ "Santa Isabel",
    origem == 'santa rita do novo destino' ~ "Santa Rita do Novo Destino",
    origem == 'sao luiz do norte' ~ "São Luiz do Norte",
    origem == 'sao patricio' ~ "São Patrício",
    origem == 'vila propicio' ~ "Vila Propício",
    origem == 'adelandia' ~ "Adelândia",
    origem == 'americano do brasil' ~ "Americano do Brasil",
    origem == 'amorinopolis' ~ "Amorinópolis",
    origem == 'aurilandia' ~ "Aurilândia",
    origem == 'buriti de goias' ~ "Buriti de Goiás",
    origem == 'cachoeira de goias' ~ "Cachoeira de Goiás",
    origem == 'corrego do ouro' ~ "Córrego do Ouro",
    origem == 'damolandia' ~ "Damolândia",
    origem == 'fazenda nova' ~ "Fazenda Nova",
    origem == 'firminopolis' ~ "Firminópolis",
    origem == 'guaraita' ~ "Guaraíta",
    origem == 'heitorai' ~ "Heitoraí",
    origem == 'ipora' ~ "Iporá",
    origem == 'israelandia' ~ "Israelândia",
    origem == 'itaberai' ~ "Itaberaí",
    origem == 'itaguari' ~ "Itaguari",
    origem == 'itaguaru' ~ "Itaguaru",
    origem == 'itapuranga' ~ "Itapuranga",
    origem == 'itaucu' ~ "Itauçu",
    origem == 'ivolandia' ~ "Ivolândia",
    origem == 'jaragua' ~ "Jaraguá",
    origem == 'jaupaci' ~ "Jaupaci",
    origem == 'jesupolis' ~ "Jesúpolis",
    origem == 'moipora' ~ "Moiporá",
    origem == 'mossamedes' ~ "Mossâmedes",
    origem == 'novo brasil' ~ "Novo Brasil",
    origem == 'petrolina de goias' ~ "Petrolina de Goiás",
    origem == 'pirenopolis' ~ "Pirenópolis",
    origem == 'sanclerlandia' ~ "Sanclerlândia",
    origem == 'santa rosa de goias' ~ "Santa Rosa de Goiás",
    origem == 'sao francisco de goias' ~ "São Francisco de Goiás",
    origem == 'sao luis de montes belos' ~ "São Luís de Montes Belos",
    origem == 'taquaral de goias' ~ "Taquaral de Goiás",
    origem == 'turvania' ~ "Turvânia",
    origem == 'uruana' ~ "Uruana",
    origem == 'abadia de goias' ~ "Abadia de Goiás",
    origem == 'abadiania' ~ "Abadiânia",
    origem == 'anapolis' ~ "Anápolis",
    origem == 'anicuns' ~ "Anicuns",
    origem == 'aparecida de goiania' ~ "Aparecida de Goiânia",
    origem == 'aracu' ~ "Araçu",
    origem == 'aragoiania' ~ "Aragoiânia",
    origem == 'avelinopolis' ~ "Avelinópolis",
    origem == 'bela vista de goias' ~ "Bela Vista de Goiás",
    origem == 'bonfinopolis' ~ "Bonfinópolis",
    origem == 'brazabrantes' ~ "Brazabrantes",
    origem == 'caldazinha' ~ "Caldazinha",
    origem == 'campo limpo de goias' ~ "Campo Limpo de Goiás",
    origem == 'caturai' ~ "Caturaí",
    origem == 'goianapolis' ~ "Goianápolis",
    origem == 'goiania' ~ "Goiânia",
    origem == 'goianira' ~ "Goianira",
    origem == 'guapo' ~ "Guapó",
    origem == 'hidrolandia' ~ "Hidrolândia",
    origem == 'inhumas' ~ "Inhumas",
    origem == 'leopoldo de bulhoes' ~ "Leopoldo de Bulhões",
    origem == 'nazario' ~ "Nazário",
    origem == 'neropolis' ~ "Nerópolis",
    origem == 'nova veneza' ~ "Nova Veneza",
    origem == 'ouro verde de goias' ~ "Ouro Verde de Goiás",
    origem == 'santa barbara de goias' ~ "Santa Bárbara de Goiás",
    origem == 'santo antonio de goias' ~ "Santo Antônio de Goiás",
    origem == 'senador canedo' ~ "Senador Canedo",
    origem == 'terezopolis de goias' ~ "Terezópolis de Goiás",
    origem == 'trindade' ~ "Trindade",
    origem == 'caiaponia' ~ "Caiapônia",
    origem == 'doverlandia' ~ "Doverlândia",
    origem == 'palestina de goias' ~ "Palestina de Goiás",
    origem == 'parauna' ~ "Paraúna",
    origem == 'sao joao da parauna' ~ "São João da Paraúna",
    origem == 'aloandia' ~ "Aloândia",
    origem == 'campestre de goias' ~ "Campestre de Goiás",
    origem == 'cezarina' ~ "Cezarina",
    origem == 'cristianopolis' ~ "Cristianópolis",
    origem == 'crominia' ~ "Cromínia",
    origem == 'edealina' ~ "Edealina",
    origem == 'indiara' ~ "Indiara",
    origem == 'jandaia' ~ "Jandaia",
    origem == 'joviania' ~ "Joviânia",
    origem == 'mairipotaba' ~ "Mairipotaba",
    origem == 'morrinhos' ~ "Morrinhos",
    origem == 'palmeiras de goias' ~ "Palmeiras de Goiás",
    origem == 'palmelo' ~ "Palmelo",
    origem == 'palminopolis' ~ "Palminópolis",
    origem == 'piracanjuba' ~ "Piracanjuba",
    origem == 'pires do rio' ~ "Pires do Rio",
    origem == 'pontalina' ~ "Pontalina",
    origem == 'professor jamil' ~ "Professor Jamil",
    origem == 'rio quente' ~ "Rio Quente",
    origem == 'santa cruz de goias' ~ "Santa Cruz de Goiás",
    origem == 'sao miguel do passa quatro' ~ "São Miguel do Passa Quatro",
    origem == 'urutai' ~ "Urutaí",
    origem == 'varjao' ~ "Varjão",
    origem == 'vicentinopolis' ~ "Vicentinópolis",
    origem == 'agua limpa' ~ "Água Limpa",
    origem == 'anhanguera' ~ "Anhanguera",
    origem == 'buriti alegre' ~ "Buriti Alegre",
    origem == 'cachoeira dourada' ~ "Cachoeira Dourada",
    origem == 'caldas novas' ~ "Caldas Novas",
    origem == 'campo alegre de goias' ~ "Campo Alegre de Goiás",
    origem == 'catalao' ~ "Catalão",
    origem == 'corumbaiba' ~ "Corumbaíba",
    origem == 'cumari' ~ "Cumari",
    origem == 'davinopolis' ~ "Davinópolis",
    origem == 'gameleira de goias' ~ "Gameleira de Goiás",
    origem == 'goiandira' ~ "Goiandira",
    origem == 'inaciolandia' ~ "Inaciolândia",
    origem == 'ipameri' ~ "Ipameri",
    origem == 'itumbiara' ~ "Itumbiara",
    origem == 'marzagao' ~ "Marzagão",
    origem == 'nova aurora' ~ "Nova Aurora",
    origem == 'orizona' ~ "Orizona",
    origem == 'ouvidor' ~ "Ouvidor",
    origem == 'panama' ~ "Panamá",
    origem == 'silvania' ~ "Silvânia",
    origem == 'tres ranchos' ~ "Três Ranchos",
    origem == 'vianopolis' ~ "Vianópolis",
    origem == 'acreuna' ~ "Acreúna",
    origem == 'bom jesus de goias' ~ "Bom Jesus de Goiás",
    origem == 'castelandia' ~ "Castelândia",
    origem == 'chapadao do ceu' ~ "Chapadão do Céu",
    origem == 'edeia' ~ "Edéia",
    origem == 'goiatuba' ~ "Goiatuba",
    origem == 'gouvelandia' ~ "Gouvelândia",
    origem == 'jatai' ~ "Jataí",
    origem == 'maurilandia' ~ "Maurilândia",
    origem == 'mineiros' ~ "Mineiros",
    origem == 'montividiu' ~ "Montividiu",
    origem == 'perolandia' ~ "Perolândia",
    origem == 'porteirao' ~ "Porteirão",
    origem == 'portelandia' ~ "Portelândia",
    origem == 'quirinopolis' ~ "Quirinópolis",
    origem == 'rio verde' ~ "Rio Verde",
    origem == 'santa helena de goias' ~ "Santa Helena de Goiás",
    origem == 'santa rita do araguaia' ~ "Santa Rita do Araguaia",
    origem == 'santo antonio da barra' ~ "Santo Antônio da Barra",
    origem == 'turvelandia' ~ "Turvelândia",
    origem == 'aparecida do rio doce' ~ "Aparecida do Rio Doce",
    origem == 'apore' ~ "Aporé",
    origem == 'cachoeira alta' ~ "Cachoeira Alta",
    origem == 'cacu' ~ "Caçu",
    origem == 'itaja' ~ "Itajá",
    origem == 'itaruma' ~ "Itarumã",
    origem == 'lagoa santa' ~ "Lagoa Santa",
    origem == 'paranaiguara' ~ "Paranaiguara",
    origem == 'sao simao' ~ "São Simão",
    origem == 'serranopolis' ~ "Serranópolis",
    
    # --- Maranhão (MA) ---
    origem == 'mara roma' ~ "(Não foi possível corrigir)",
    origem == 'milagres do maranhao' ~ "Milagres do Maranhão",
    
    # --- Minas Gerais (MG) ---
    origem == 'limeira doeste' ~ "Limeira do Oeste",
    origem == 'vitoria' ~ "Santa Vitória",
    origem == 'cachoeira do pajeu' ~ "Cachoeira do Pajeú",
    origem == 'santa do paraiso' ~ "Santana do Paraíso",
    origem == 'sao geraldo do baixo' ~ "São Geraldo do Baixio",
    origem == 'frei inocencia' ~ "Frei Inocêncio",
    origem == 'maravilha' ~ "(Não é um município de MG)",
    origem == 'santa cruz do escal vado' ~ "Santa Cruz do Escalvado",
    origem == 'santanado manhuacu' ~ "Santana do Manhuaçu",
    origem == 'guarupe' ~ "(Não foi possível corrigir)",
    origem == 'tres pontas-boa esperanca' ~ "Três Pontas e Boa Esperança",
    origem == 'englobando 82 municipios: alfenas' ~ "Alfenas",
    origem == 'verdelandiabonito de minas' ~ "Verdelândia e Bonito de Minas",
    origem == 'conego ma- rinho' ~ "Cônego Marinho",
    origem == 'gua- raciama' ~ "Guaraciama",
    origem == 'no- vorizonte' ~ "Novorizonte",
    origem == 'varjao de minasvazantecoromandel' ~ "Varjão de Minas, Vazante e Coromandel",
    
    # --- Mato Grosso (MT) ---
    origem == 'cuiabae varzea grande' ~ "Cuiabá e Várzea Grande",
    origem == 'vila bela da s trindade' ~ "Vila Bela da Santíssima Trindade",
    origem == 'pontes' ~ "Pontes e Lacerda",
    origem == 'lacerda' ~ "Pontes e Lacerda",
    origem == 'conquista d oeste' ~ "Conquista d'Oeste",
    origem == 'vale do sao domingos' ~ "Vale de São Domingos",
    origem == 'sao jose dos 4 marcos' ~ "São José dos Quatro Marcos",
    origem == 'gloria d oeste' ~ "Glória d'Oeste",
    origem == 'figueiropolis d oeste' ~ "Figueirópolis d'Oeste",
    origem == 'alto garca' ~ "Alto Garças",
    origem == 'mirassol d oeste' ~ "Mirassol d'Oeste",
    origem == 'lambari d oeste' ~ "Lambari d'Oeste",
    origem == 'n senhora do livramento' ~ "Nossa Senhora do Livramento",
    
    # --- Pará (PA) ---
    origem == 'monte alegre de goias' ~ "Monte Alegre",
    origem == 'monjui dos campos' ~ "Mojuí dos Campos",
    origem == 'ucurui' ~ "Tucuruí",
    origem == 'novo repartimento e breu branco' ~ "Novo Repartimento e Breu Branco",
    origem == 'igarape miri' ~ "Igarapé-Miri",
    origem == 'tracuateua e viseu' ~ "Tracuateua e Viseu",
    
    # --- Paraíba (PB) ---
    origem == 'poco jose de moura' ~ "Poço de José de Moura",
    origem == 'santa terezinha' ~ "Santa Teresinha",
    origem == 'sao jose do espinharas' ~ "São José do Espinharas",
    origem == 'riachaodo bacamarte' ~ "Riachão do Bacamarte",
    origem == 'sao sebastiaodelagoa de roca' ~ "São Sebastião de Lagoa de Roça",
    origem == 'aguabranca' ~ "Água Branca",
    origem == 'maedagua' ~ "Mãe d'Água",
    origem == 'saojosedecaiana' ~ "São José de Caiana",
    origem == 'tavares todos os municipios estaolocalizados nos limites da mesorregiao do sertao' ~ "Tavares",
    origem == 'nas microrregioes de catole do rocha' ~ "Catolé do Rocha",
    origem == 'serido oriental' ~ "(Não é um município)",
    origem == 'lagoa grande' ~ "(Não é um município da PB)",
    
    # --- Pernambuco (PE) ---
    origem == 'franio' ~ "(Não foi possível corrigir)",
    origem == 'abare' ~ "Abaré",
    origem == 'chorrocho' ~ "Chorrochó",
    origem == 'curaca' ~ "Curaçá",
    origem == 'gloria' ~ "Glória",
    origem == 'macurure' ~ "Macururé",
    origem == 'rodelas' ~ "Rodelas",
    origem == 'abreu' ~ "Abreu e Lima",
    origem == 'lima' ~ "Abreu e Lima",
    origem == 'agua peta' ~ "Água Preta",
    origem == 'gameleiras' ~ "Gameleira",
    
    # --- Piauí (PI) ---
    origem == 'sao joao da fronteira e sao jose do divino' ~ "São João da Fronteira e São José do Divino",
    origem == 'entorno teresina' ~ "(Não é um município)",
    origem == 'alto parnaiba' ~ "Alto Parnaíba",
    
    # --- Paraná (PR) ---
    origem == 'uniflor e xambre' ~ "Uniflor e Xambrê",
    origem == 'uniao da vitoria e ventania' ~ "União da Vitória e Ventania",
    
    # --- Rio de Janeiro (RJ) ---
    origem == 'conceicao do macabu' ~ "Conceição de Macabu",
    origem == 'teresopolis e trajano de moraes' ~ "Teresópolis e Trajano de Moraes",
    origem == 'sao jose de uba e varre-sai' ~ "São José de Ubá e Varre-Sai",
    origem == 'armacao de buzios' ~ "Armação dos Búzios",
    origem == 'saquarema e silva jardim' ~ "Saquarema e Silva Jardim",
    origem == 'sao francisco do itabapoana' ~ "São Francisco de Itabapoana",
    
    # --- Rio Grande do Norte (RN) ---
    origem == 'monte alegre de goias' ~ "Monte Alegre",
    origem == 'joao camara/rn abrangencia: bento fernandes' ~ "João Câmara e Bento Fernandes",
    origem == 'passa' ~ "Passa e Fica",
    origem == 'fica' ~ "Passa e Fica",
    origem == 'sao rafae' ~ "São Rafael",
    origem == 'lagoa d anta' ~ "Lagoa d'Anta",
    origem == 'doutor' ~ "Doutor Severiano",
    origem == 'severiano' ~ "Doutor Severiano",
    origem == 'olho dagua dos borges' ~ "Olho-d'Água do Borges",
    origem == 'sao bento do borte' ~ "São Bento do Norte",
    origem == 'senador georgino' ~ "Senador Georgino Avelino",
    origem == 'velino' ~ "Senador Georgino Avelino",
    origem == 'ceara- mirim' ~ "Ceará-Mirim",
    origem == 'tenente lautrentino cruz' ~ "Tenente Laurentino Cruz",
    origem == 'governador dix- sept rosado' ~ "Governador Dix-Sept Rosado",
    origem == 'triunfo potiguar e upanema' ~ "Triunfo Potiguar e Upanema",
    origem == 'venha- ver' ~ "Venha-Ver",
    
    # --- Rondônia (RO) ---
    origem == 'pimenteiras doeste' ~ "Pimenteiras do Oeste",
    origem == 'porto velho alto madeira' ~ "Porto Velho",
    origem == 'baixo madeira' ~ "(Não é um município)",
    origem == 'ponta do abuna' ~ "(Não é um município)",
    origem == 'porto velho ponta do abuna' ~ "Porto Velho",
    origem == 'alto madeira' ~ "(Não é um município)",
    
    # --- Roraima (RR) ---
    origem == 'sao luis' ~ "São Luís",
    
    # --- Rio Grande do Sul (RS) ---
    origem == 'estrela doeste' ~ "Estrela Velha",
    origem == 'sao' ~ "São Vicente do Sul",
    origem == 'icente do sul' ~ "São Vicente do Sul",
    origem == 'barra do' ~ "Barra do Ribeiro",
    origem == 'ibeiro' ~ "Barra do Ribeiro",
    origem == 'minas do' ~ "Minas do Leão",
    origem == 'eao' ~ "Minas do Leão",
    origem == 'sentinela' ~ "Sentinela do Sul",
    origem == 'o sul' ~ "Sentinela do Sul",
    origem == 'sant ana do livramento' ~ "Sant'Ana do Livramento",
    origem == 'porto xavier e rolador' ~ "Porto Xavier e Rolador",
    origem == 'tres forquilhas e xangri-la o mrt 08 representa boa parte da faixa litoranea do estado' ~ "Três Forquilhas e Xangri-lá",
    origem == 'desde o litoral norte ate o municipio de sao jose do norte' ~ "São José do Norte",
    origem == '53 municipios' ~ "(Não é um município)",
    origem == 'dentre eles destacam-se: santa cruz do sul' ~ "Santa Cruz do Sul",
    origem == 'mais ao centro deste mercado' ~ "(Não é um município)",
    origem == 'a oeste' ~ "(Não é um município)",
    origem == 'ja ao sul do mercado estao os municipios de pantano grande' ~ "Pantano Grande",
    origem == 'a leste' ~ "(Não é um município)",
    origem == 'o vale do taquari' ~ "(Não é um município)",
    
    # --- Santa Catarina (SC) ---
    origem == 'xaxim esta localizada na mesorregiao oeste do estado de santa catarina' ~ "Xaxim",
    origem == 'gorolandia' ~ "(Não foi possível corrigir)",
    origem == 'vidal ramaos' ~ "Vidal Ramos",
    origem == 'coronel martns' ~ "Coronel Martins",
    origem == 'lageado grande' ~ "Lajeado Grande",
    origem == 'xaxia e' ~ "Xaxim",
    origem == 'iporanga' ~ "Ituporanga",
    origem == 'chapadao do lajeado' ~ "Chapadão do Lageado",
    origem == 'videira esta localizada na mesorregiao oeste do estado de santa catarina' ~ "Videira",
    
    # --- Sergipe (SE) ---
    origem == 'indiarobae pedrinhas' ~ "Indiaroba e Pedrinhas",
    origem == 'taporanga dajuda' ~ "Itaporanga d'Ajuda",
    origem == 'caninde do sao francisco' ~ "Canindé de São Francisco",
    origem == 'monte alegre de goias' ~ "Monte Alegre de Sergipe",
    origem == 'sao miguel do aleixo cumbe' ~ "São Miguel do Aleixo e Cumbe",
    
    # --- São Paulo (SP) ---
    origem == 'americo de cam- pos' ~ "Américo de Campos",
    origem == 'gua- rani doeste' ~ "Guarani d'Oeste",
    origem == 'me- ridiano' ~ "Meridiano",
    origem == 'nova luzita- nia' ~ "Nova Luzitânia",
    origem == 'poti- rendaba' ~ "Potirendaba",
    origem == 'dra- cena' ~ "Dracena",
    origem == 'na- randiba' ~ "Narandiba",
    origem == 'nova indepedencia' ~ "Nova Independência",
    origem == 'salmorao' ~ "Salmourão",
    origem == 'ca- juru' ~ "Cajuru",
    origem == 'elisario' ~ "Elisiário",
    origem == 'jardi- nopolis' ~ "Jardinópolis",
    origem == 'pa- trocinio pta' ~ "Patrocínio Paulista",
    origem == 'itapecerica da terra' ~ "Itapecerica da Serra",
    origem == 'santa izabel' ~ "Santa Isabel",
    origem == 'jan- dira' ~ "Jandira",
    origem == 'campo limpo pau- lista' ~ "Campo Limpo Paulista",
    origem == 'embu' ~ "Embu das Artes",
    origem == 'pira- caia' ~ "Piracaia",
    origem == 'tremembe e redencao as serra' ~ "Tremembé e Redenção da Serra",
    origem == 'de guaratingueta' ~ "Guaratinguetá",
    origem == 'buriti' ~ "Buritizal",
    origem == 'capi- vari' ~ "Capivari",
    origem == 'horto- landia' ~ "Hortolândia",
    origem == 'santa barbara do oeste' ~ "Santa Bárbara d'Oeste",
    origem == 'alvin- landia' ~ "Alvinlândia",
    origem == 'ca- felandia' ~ "Cafelândia",
    origem == 'gua- embe' ~ "Guaimbê",
    origem == 'piratininta' ~ "Piratininga",
    origem == 'vera cruz aguas de santa barbara' ~ "Vera Cruz e Águas de Santa Bárbara",
    origem == 'tejuca' ~ "Tejupá",
    origem == 'ipira' ~ "Iporanga",
    
    # IMPORTANTE: Mantém todos os outros valores que não foram corrigidos
    .default = origem
  ))
