project:
  type: website

bibliography: refs.bib

website:
  title: "analises_banco_completo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-fold: true


