name: Publish Quarto site

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # necessário para publicar no gh-pages

    steps:
      - uses: actions/checkout@v4

      # Instalar Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # Linguagens (habilite as que usar)
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Dependências do projeto (opcionais)
      - name: Instalar deps do projeto (opcional)
        working-directory: site
        run: |
          pip install -r requirements.txt || true
          Rscript -e 'if ("renv" %in% rownames(installed.packages())) renv::restore(prompt = FALSE) else invisible(TRUE)'

      # Renderizar site (a partir da pasta `site`)
      - name: Render
        run: quarto render
        working-directory: site

      # Publicar em GitHub Pages (docs gerados dentro de site/docs)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/docs
